### PR TITLE
Fix sails hook orm v4.01 upgrade issue

### PR DESCRIPTION
**Pull request by maruthim**
### Summary
Fix failure in upgrading sails-hook-orm to v4.0.1

### CODE REVIEW

**Comment by shashankmeyar** [comment]
Hi @maruthim ,
Are you sure, you want to merge this into this branch directly nutanix:upgrade/sailsjs? (Is this a breaking change?)
or 
start using it from this branch itself?
Even I am not sure, how many other projects are currently using it from this branch **nutanix:upgrade/sailsjs**

**Comment by maruthim** [comment]
> Hi @maruthim , Are you sure, you want to merge this into this branch directly nutanix:upgrade/sailsjs? (Is this a breaking change?) or start using it from this branch itself? Even I am not sure, how many other projects are currently using it from this branch **nutanix:upgrade/sailsjs**

@shashankmeyar  As per the waterline standard interface, all the orm adapters have to expose `datastores`.
and this is not braking but just an extension.

**Review by shashankmeyar — APPROVED** [review]
Shall I merge this then?

**Comment by maruthim** [comment]
> Shall I merge this then?

Yes.

**Comment by shashankmeyar** [comment]
@maruthim I am not getting an option to merge this pull request. Not sure why, is it because you raised it from your forked repo?

**Comment by maruthim** [comment]
> @maruthim I am not getting an option to merge this pull request. Not sure why, is it because you raised it from your forked repo?

@vinay-kashyap Can you merge the PR?

**Pull request merged**
